services:
  backend:
    build:
      context: .
      dockerfile: Prototype/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ~/.nuget/packages:/root/.nuget/packages
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: