services:
  frontend:
    build:
      target: dev
    volumes:
      # Mount source for live reload
      - ./Prototype/ClientApp:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USE_POLLING=true
      - BROWSER=none
    restart: unless-stopped

  backend:
    build:
      target: dev
    volumes:
      # Mount backend source for hot reload (cached = better perf on macOS/Windows)
      - ./Prototype:/src/Prototype:cached
      # Use local NuGet cache for faster restore
      - ~/.nuget/packages:/root/.nuget/packages:cached
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped